### ISSUE TITLE
v0.0.14 bug

### ISSUE THREAD

**Issue by shellvip** [KingPixil/moonify#1]
```
<template>
asd
</template>
```
this is OK in v0.0.12 but not working in v0.0.14:
`Uncaught TypeError: Cannot read property 'length' of undefined.`

**Comment by kbrsh** [comment]
In v0.0.12, a `div` was automatically wrapped around the component. In v0.0.14, more control is allowed, and the component is the actual contents of the `template` tag.

And if you didn't know, Moon doesn't allow text-only components, so you should have at least some sort of element.
