### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by shellvip** [KingPixil/moonify#2]
moonify v0.0.14:
```
Uncaught TypeError: Cannot read property 'type' of undefined  
   at hydrate (node_modules\moonjs\dist\node_modules\moonjs\dist\moon.js:724)
```
I have a .moon component with the below template:
```
<template>
<div>

</div>
</template>
```
the vnode is undefined in function hydrate.

**Comment by kbrsh** [comment]
Yeah, this is fixed in Moon v0.11.0.

For now, just use an older Moonify version, as there are issues with it being compatible with Moon v0.10.0. When you are ready to upgrade Moon, update Moonify to v0.0.14.
